# Generated by Django 3.1.6 on 2022-11-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_public_key', models.TextField(blank=True, null=True)),
                ('google_maps_key', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=250)),
                ('ville', models.CharField(max_length=32)),
                ('code_postale', models.CharField(max_length=32)),
                ('montant', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Panier_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('supplements', models.TextField(null=True)),
                ('information', models.TextField(null=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infos_menus', models.TextField(null=True)),
                ('produits', models.ManyToManyField(blank=True, to='paiement.Panier_produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('methode_vente', models.CharField(max_length=50, null=True)),
                ('prix_totale', models.FloatField(default=0.0)),
                ('est_vue', models.BooleanField(default=False)),
                ('est_livre', models.BooleanField(default=False)),
                ('reference', models.CharField(default='', max_length=5, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paiement.client')),
                ('panier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paiement.panier')),
            ],
        ),
    ]
