# Generated by Django 3.1.6 on 2022-11-24 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Info_Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilite_restaurant', models.BooleanField(default=False, null=True)),
                ('disponibilite_livraison', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type_supplement', models.CharField(blank=True, choices=[('Pain', 'pain'), ('Viande', 'viande'), ('Sur_frite', 'sur_frite'), ('Sauce', 'sauce'), ('Crudite', 'crudite'), ('Fromage', 'fromage'), ('Dessert', 'dessert'), ('Boisson', 'boisson'), ('TaillePizza', 'TaillePizza')], max_length=100, null=True)),
                ('prix', models.FloatField(blank=True, default=0)),
                ('disponibilite', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/images')),
                ('prix', models.FloatField(blank=True, default=0)),
                ('disponibilite', models.BooleanField(default=False, null=True)),
                ('commentaire_produit', models.TextField(blank=True, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.categorie')),
            ],
        ),
    ]
